### ISSUE TITLE
Keyboard short cut

### ISSUE THREAD

**Issue by B-iggy** [Flamenco/grav-plugin-quicksave#1]
Hey there!

I really like your work and it improves the workflow by over 100% at the moment.
Unfortunately nerfed by 100% again because I have to move the mouse to that far off button.

Can I somehow support you by implementing / overwriting the default CTRL + S shortcut with your version?

Either a hint on how / where I could code it or a 5 euro donation for a big coffee for you would be fine? :)

**Comment by Flamenco** [comment]
Yep, quicksave, back, and refresh makes my life much easier ;)  I will take a look at the Grav code and see what we can do about a keyboard shortcut.

@B-iggy Would you be OK with shift-control-s so as to not mess up the default.

**Comment by B-iggy** [comment]
Yes, this would be great as well! :) Thank you!

**Comment by Flamenco** [comment]
I went with shift-command-a for a variety of reasons. 

This is **not** enabled by default.  Turn it on in the plugin options.

This plugin now has a dependency on our core-service-manager; that should install automatically.  I cant release this until the latest core-service-manager gets picked up by Grav though, so wait for v0.1.4 to show up in the next day or so.

**Comment by B-iggy** [comment]
Awesome!! Thank you very much!

**Comment by Flamenco** [comment]
I confirmed that the dependency installs as expected.  I will issue a PR with the admin plugin to not consume both shift-control-s and control-s

**Comment by Flamenco** [comment]
https://github.com/getgrav/grav-plugin-admin/issues/1382

**Comment by Flamenco** [comment]
https://github.com/getgrav/grav-plugin-admin/pull/1383

**Comment by B-iggy** [comment]
You made it in :) 

https://github.com/getgrav/grav-plugin-admin/commit/6e770577e2c8c50433f34fdd62d29554e9a62b8d

https://github.com/getgrav/grav-plugin-admin/commit/ca4d1ca55c95b48bb094ce03e3b39dd75ac0c6f3

**Comment by Flamenco** [comment]
@B-iggy I will switch to shift-control-s ASAP.  I hope you are not too accustomed to the current way...

**Comment by Flamenco** [comment]
https://github.com/Flamenco/grav-plugin-quicksave/releases
