### ISSUE TITLE
Conflict with TinyMCE : The content has not changed

### ISSUE THREAD

**Issue by Heraes-git** [Flamenco/grav-plugin-quicksave#2]
Hello,

When pushing the "Save Content" button, it says "The content has not changed", wether or not I modify the page's text or add something into it.

I have TinyMCE installed. I tested to disable it, and it solved the problem. So it's a conflict

**Comment by Flamenco** [comment]
Hi @Romarain,

Thank you for reporting your issue.

I have not used the TinyMCE plugin, but will install it and have a look.  I am familiar with the TinyMCE API so it should not be too complicated.

With that said, there is a chance the issue will have to be solved on the TinyMCE plugin side.

**Comment by Flamenco** [comment]
This has been fixed in release 1.0.10
