### ISSUE TITLE
Error 500 when saving

### ISSUE THREAD

**Issue by CherryDT** [Flamenco/grav-plugin-quicksave#3]
Error:

```json
{
  "error": {
    "type": "RuntimeException",
    "message": "Template \"modular\/text.json.twig\" is not defined.",
    "file": "xxx\/system\/src\/Grav\/Common\/Twig\/Twig.php",
    "line": 292
  }
}
```

Grav version 1.6.9

I was trying to save a modular page section.

**Comment by Flamenco** [comment]
@CherryDT Has this plugin worked for you in the past but failed after an upgrade or installation of another plugin?

**Comment by CherryDT** [comment]
No, I installed it for the first time and it failed right away.

Other plugins I had installed:

* admin
* email
* error
* featherlight
* form
* langswitcher
* login
* problems
* shortcode-core
* shortcode-ui

I was using a slightly customized theme inherited from "quark".

**Comment by Flamenco** [comment]
We have released a new version of this plugin.  Please reopen if this is still an issue.
